# Generated by Django 5.2.17 on 2026-10-05 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_trade", "Новая сделка"),
                            ("tp_sl", "TP/SL"),
                            ("daily_digest", "Дайджест"),
                            ("test", "Тестовое"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Отправлено"), ("failed", "Ошибка")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог уведомления",
                "verbose_name_plural": "Логи уведомлений",
                "db_table": "notifications_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Telegram chat_id",
                    ),
                ),
                (
                    "telegram_linked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Привязан к Telegram"
                    ),
                ),
                (
                    "notify_new_trade",
                    models.BooleanField(default=True, verbose_name="Новая сделка"),
                ),
                (
                    "notify_tp_sl",
                    models.BooleanField(default=True, verbose_name="Достижение TP/SL"),
                ),
                (
                    "notify_daily_digest",
                    models.BooleanField(default=True, verbose_name="Утренний дайджест"),
                ),
                (
                    "digest_hour",
                    models.IntegerField(default=9, verbose_name="Час дайджеста (UTC)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
                "db_table": "notifications_settings",
            },
        ),
    ]
