# Generated by Django 5.2.17 on 2026-10-05 00:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Символ"
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy (Long)"), ("sell", "Sell (Short)")],
                        max_length=10,
                        verbose_name="Сторона",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыта"),
                            ("closed", "Закрыта"),
                            ("cancelled", "Отменена"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Цена входа"
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="Цена выхода",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Объём"
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="Stop Loss",
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="Take Profit",
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="PnL",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Комиссия",
                    ),
                ),
                ("opened_at", models.DateTimeField(verbose_name="Открыта")),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Закрыта"),
                ),
                (
                    "strategy",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Стратегия",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Теги"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "emotion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calm", "Спокойствие"),
                            ("fomo", "FOMO"),
                            ("fear", "Страх"),
                            ("greed", "Жадность"),
                            ("revenge", "Тильт / Реванш"),
                            ("confidence", "Уверенность"),
                        ],
                        max_length=20,
                        verbose_name="Эмоция",
                    ),
                ),
                (
                    "followed_plan",
                    models.BooleanField(default=True, verbose_name="Следовал плану"),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="trades/%Y/%m/",
                        verbose_name="Скриншот",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Вручную"),
                            ("mt5", "MetaTrader 5"),
                            ("api", "API"),
                            ("import", "Импорт"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Внешний ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сделка",
                "verbose_name_plural": "Сделки",
                "db_table": "trades_trade",
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-opened_at"],
                        name="trades_trad_user_id_efbe9c_idx",
                    ),
                    models.Index(
                        fields=["user", "symbol"], name="trades_trad_user_id_089547_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="trades_trad_user_id_aee238_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id__gt", "")),
                        fields=("user", "source", "external_id"),
                        name="unique_external_trade_per_user",
                    )
                ],
            },
        ),
    ]
