# Generated by Django 5.2.17 on 2026-10-05 16:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trade",
            options={
                "ordering": ["-opened_at"],
                "verbose_name": "РЎРґРµР»РєР°",
                "verbose_name_plural": "РЎРґРµР»РєРё",
            },
        ),
        migrations.AlterField(
            model_name="trade",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Р—Р°РєСЂС‹С‚Р°"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="commission",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=20,
                verbose_name="РљРѕРјРёСЃСЃРёСЏ",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="emotion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calm", "РЎРїРѕРєРѕР№СЃС‚РІРёРµ"),
                    ("fomo", "FOMO"),
                    ("fear", "РЎС‚СЂР°С…"),
                    ("greed", "Р–Р°РґРЅРѕСЃС‚СЊ"),
                    ("revenge", "РўРёР»СЊС‚ / Р\xa0РµРІР°РЅС€"),
                    ("confidence", "РЈРІРµСЂРµРЅРЅРѕСЃС‚СЊ"),
                ],
                max_length=20,
                verbose_name="Р\xadРјРѕС†РёСЏ",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="entry_price",
            field=models.DecimalField(
                decimal_places=8, max_digits=20, verbose_name="Р¦РµРЅР° РІС…РѕРґР°"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="exit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Р¦РµРЅР° РІС‹С…РѕРґР°",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="Р’РЅРµС€РЅРёР№ ID",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="followed_plan",
            field=models.BooleanField(
                default=True, verbose_name="РЎР»РµРґРѕРІР°Р» РїР»Р°РЅСѓ"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Р—Р°РјРµС‚РєРё"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="opened_at",
            field=models.DateTimeField(verbose_name="РћС‚РєСЂС‹С‚Р°"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="quantity",
            field=models.DecimalField(
                decimal_places=8, max_digits=20, verbose_name="РћР±СЉС‘Рј"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="trades/%Y/%m/",
                verbose_name="РЎРєСЂРёРЅС€РѕС‚",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="side",
            field=models.CharField(
                choices=[("buy", "Buy (Long)"), ("sell", "Sell (Short)")],
                max_length=10,
                verbose_name="РЎС‚РѕСЂРѕРЅР°",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Р’СЂСѓС‡РЅСѓСЋ"),
                    ("mt5", "MetaTrader 5"),
                    ("api", "API"),
                    ("import", "Р\x98РјРїРѕСЂС‚"),
                ],
                default="manual",
                max_length=10,
                verbose_name="Р\x98СЃС‚РѕС‡РЅРёРє",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "РћС‚РєСЂС‹С‚Р°"),
                    ("closed", "Р—Р°РєСЂС‹С‚Р°"),
                    ("cancelled", "РћС‚РјРµРЅРµРЅР°"),
                ],
                default="open",
                max_length=10,
                verbose_name="РЎС‚Р°С‚СѓСЃ",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="strategy",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="РЎС‚СЂР°С‚РµРіРёСЏ",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="symbol",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="РЎРёРјРІРѕР»"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="РўРµРіРё"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ",
            ),
        ),
    ]
