# Generated by Django 5.2.17 on 2026-10-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Символ"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Цена"
                    ),
                ),
                (
                    "change_24h",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="Изм. 24ч (%)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("coingecko", "CoinGecko"),
                            ("binance", "Binance"),
                            ("mt5", "MetaTrader 5"),
                            ("manual", "Вручную"),
                        ],
                        default="coingecko",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="В избранном"),
                ),
            ],
            options={
                "verbose_name": "Цена",
                "verbose_name_plural": "Цены",
                "db_table": "market_price_snapshot",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Символ"
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        default="1h", max_length=5, verbose_name="Таймфрейм"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Время")),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Open"
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="High"
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Low"
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Close"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=8, default=0, max_digits=30, verbose_name="Объём"
                    ),
                ),
            ],
            options={
                "verbose_name": "Свеча",
                "verbose_name_plural": "Свечи",
                "db_table": "market_candle",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timeframe", "-timestamp"],
                        name="market_cand_symbol_47196f_idx",
                    )
                ],
                "unique_together": {("symbol", "timeframe", "timestamp")},
            },
        ),
    ]
